apiVersion: batch/v1
kind: Job
metadata:
  name: shorts-generator-test-manual
  namespace: shorts-generator
spec:
  template:
    spec:
      containers:
      - name: shorts-generator
        image: ghcr.io/juninmd/shorts-generator:latest
        imagePullPolicy: Always
        command: ["pnpm", "run", "generate"]
        args: ["--url", "https://www.youtube.com/watch?v=ybcOKbe1H1c", "--clips", "1"]
        env:
        - name: YOUTUBE_CHANNELS
          value: "@FreiGilsonSomdoMonteOFICIAL"
        - name: WHISPER_CHUNK_DURATION_SEC
          value: "120"
        - name: WHISPER_BASE_URL
          value: http://whisper.ai.svc.cluster.local:9000
        - name: AI_MODEL
          value: "cloud/gemma3"
        - name: LITELLM_BASE_URL
          value: http://litellm.ai.svc.cluster.local:4000/v1
        - name: LITELLM_KEY
          valueFrom:
            secretKeyRef:
              name: shorts-generator-secret
              key: LITELLM_KEY
        - name: YOUTUBE_REFRESH_TOKEN
          valueFrom:
            secretKeyRef:
              name: shorts-generator-secret
              key: YOUTUBE_REFRESH_TOKEN
        - name: YOUTUBE_CLIENT_ID
          valueFrom:
            secretKeyRef:
              name: shorts-generator-secret
              key: YOUTUBE_CLIENT_ID
        - name: YOUTUBE_CLIENT_SECRET
          valueFrom:
            secretKeyRef:
              name: shorts-generator-secret
              key: YOUTUBE_CLIENT_SECRET
        - name: ENABLE_YOUTUBE
          value: "true"
        - name: TELEGRAM_BOT_TOKEN
          valueFrom:
            secretKeyRef:
              name: shorts-generator-secret
              key: TELEGRAM_BOT_TOKEN
        - name: TELEGRAM_CHAT_ID
          valueFrom:
            secretKeyRef:
              name: shorts-generator-secret
              key: TELEGRAM_CHAT_ID
        resources:
          limits:
            cpu: "1"
            memory: "3Gi"
          requests:
            cpu: "10m"
            memory: "1Gi"
      restartPolicy: Never
      imagePullSecrets:
      - name: ghcr-pull-secret
  backoffLimit: 0
