import { describe, it, expect } from "vitest";
import fs from "node:fs";
import path from "node:path";
import { analyzeTranscript } from "../../src/core/analyzer.js";
import type { Transcript, PipelineConfig } from "../../src/types.js";
import { logger } from "../../src/core/logger.js";

describe("LLM Analysis Integration", () => {
  const config: PipelineConfig = {
    aiProvider: (process.env.AI_PROVIDER as any) || "ollama",
    aiModel: process.env.AI_MODEL || "qwen3:1.7b",
    aiTimeoutMs: 300_000,
    ollamaBaseUrl: process.env.OLLAMA_BASE_URL || "http://localhost:11434",
    openrouterApiKey: process.env.OPENROUTER_API_KEY || "",
    minShortDuration: 15,
    maxShortDuration: 59,
    maxClipsOverride: 3,
  } as PipelineConfig;

  it("should generate clips from the saved transcript asset using local LLM", async () => {
    const transcriptPath = path.join(process.cwd(), "tests", "assets", "transcript.txt");
    if (!fs.existsSync(transcriptPath)) {
      logger.warn("Asset transcript.txt not found, skipping test.");
      return;
    }

    const fullText = fs.readFileSync(transcriptPath, "utf-8");
    const lines = fullText.split("\n");
    const segments = lines.map(line => {
      const match = line.match(/\[(\d+):(\d+)-(\d+):(\d+)\] (.*)/);
      if (!match) return null;
      const [_, m1, s1, m2, s2, text] = match;
      return {
        start: parseInt(m1!) * 60 + parseInt(s1!),
        end: parseInt(m2!) * 60 + parseInt(s2!),
        text: text!
      };
    }).filter(Boolean) as any[];

    const transcript: Transcript = {
      videoId: "ybcOKbe1H1c",
      duration: segments[segments.length - 1].end,
      segments,
      words: [],
      fullText,
      language: "pt"
    };

    logger.info("Running real LLM analysis on saved transcript...");
    const clips = await analyzeTranscript(transcript, "Teste Integrado", "Frei Gilson", config);
    
    logger.info({ clipsCount: clips.length }, "LLM Analysis finished");
    
    if (clips.length > 0) {
      clips.forEach(clip => {
        expect(clip.duration).toBeLessThanOrEqual(config.maxShortDuration);
        expect(clip.duration).toBeGreaterThanOrEqual(config.minShortDuration);
        logger.info({ title: clip.title, duration: clip.duration.toFixed(1) }, "Clip generated by LLM");
      });
    } else {
      logger.warn("LLM returned no clips for this transcript.");
    }
  }, 300_000); // 5 minutes timeout for local LLM
});
