import { describe, it, expect } from "vitest";
import fs from "node:fs";
import path from "node:path";
import { analyzeTranscript } from "../../src/core/analyzer.js";
import type { Transcript } from "../../src/types.js";
import { logger } from "../../src/core/logger.js";
import { loadConfig } from "../../src/core/config.js";

describe.skipIf(process.env.RUN_LLM_INTEGRATION !== "true")("LLM Analysis Integration", () => {
  const config = loadConfig({
    minShortDuration: 15,
    maxShortDuration: 59,
    maxClipsOverride: 3,
    ...(process.env.LLM_TEST_MODEL ? { aiModel: process.env.LLM_TEST_MODEL } : {}),
  });

  it("should generate clips from the saved transcript asset using local LLM", async () => {
    const transcriptPath = path.join(process.cwd(), "tests", "assets", "transcript.txt");
    if (!fs.existsSync(transcriptPath)) {
      logger.warn("Asset transcript.txt not found, skipping test.");
      return;
    }

    const fullText = fs.readFileSync(transcriptPath, "utf-8");
    const lines = fullText.split("\n");
    const segments = lines.map(line => {
      const match = line.match(/\[(\d+):(\d+)-(\d+):(\d+)\] (.*)/);
      if (!match) return null;
      const [_, m1, s1, m2, s2, text] = match;
      return {
        start: parseInt(m1!) * 60 + parseInt(s1!),
        end: parseInt(m2!) * 60 + parseInt(s2!),
        text: text!
      };
    }).filter(Boolean) as any[];

    const transcript: Transcript = {
      videoId: "ybcOKbe1H1c",
      duration: segments[segments.length - 1].end,
      segments,
      words: [],
      fullText,
      language: "pt"
    };

    logger.info("Running real LLM analysis on saved transcript...");
    const clips = await analyzeTranscript(transcript, "Teste Integrado", "Frei Gilson", config);
    
    logger.info({ clipsCount: clips.length }, "LLM Analysis finished");
    
    expect(clips.length).toBeGreaterThan(0);
    clips.forEach(clip => {
      expect(clip.duration).toBeLessThanOrEqual(config.maxShortDuration);
      expect(clip.duration).toBeGreaterThanOrEqual(config.minShortDuration);
      expect(clip.viralScore).toBeGreaterThanOrEqual(config.minViralScore);
      logger.info({ title: clip.title, duration: clip.duration.toFixed(1) }, "Clip generated by LLM");
    });
  }, 600_000);
});
