name: Security Scan

on:
  workflow_dispatch:
  push:
    branches: [main, master]

permissions:
  contents: read

jobs:
  gitleaks:
    uses: juninmd/base-actions/.github/workflows/reusable-security-scan.yml@f23703faf50a6fa3740ef7ac046765a15a6e6c49
